### ISSUE TITLE
Make sure everyone is on GitHub

### ISSUE THREAD

**Issue by ghost** [PSB-NEFSC-NMFS-NOAA/PSB-Openscapes-Initiative#1]
Josh (@jmhatch), Leah (@leeyuhc), and Doug (@Dsigourney24) are on GitHub. What about Beth?

**Comment by jmhatch** [comment]
Everyone should be an admin of this repo, let me know if that isn't the case.

**Comment by Turtle-PSB-NOAA** [comment]
Beth is @beth

**Comment by ghost** [comment]
Beth is @bethjosephson!

**Comment by ghost** [comment]
Everyone is on GitHub! :heart_eyes:
